[window]
padding.x = 0
padding.y = 5

opacity = 1
blur = false

decorations = "none"

[font]
normal.family = "Hurmit Nerd Font Mono"
size = 6

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/zsh"

[general]
import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]
